/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Button, StyleSheet, Text, View, NativeModules } from 'react-native';

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆AtomPayment example☆</Text>
        <Text style={styles.instructions}>STATUS: loaded</Text>
        <Text style={styles.welcome}>☆☆☆</Text>
        <Button title={'Pay Now'} onPress={this.onPressPayNow} />
      </View>
    );
  }

  onPressPayNow() {
    let atomPayment = NativeModules.AtomPayment;
    let netB = { discriminator: 'All', 
    merchantId: '197', 
    txnscamt: '0', 
    loginid: '197', 
    password: 'Test@123', 
    txncurr: 'INR', 
    clientcode: '007',
    custacc: '100000036600',
    amt: '100.00',
    txnid: '015',
    date: '23/08/2019 11:57:00',
    bankid: '2001',
    signatureRequest: 'KEY123657234',
    signatureResponse: 'KEYRESP123657234',
    prodid:'NSE',
    isLive: false,
    ru: 'https://paynetzuat.atomtech.in/mobilesdk/param',
    channelid: 'INT',
   };
  
   // Below are the optional values
            netB.customerName = "ABC";
            netB.customerEmailID = "abc@gmail.com";
            netB.customerMobileNo = "5555555555";
            netB.billingAddress = "Pune";
            netB.optionalUdf9 = "Chetan";
    atomPayment.goForAtomPayment(netB, (error, response) => {
      if (error) {
        console.error(error);
      } else {
        console.error(response);
      }
    });
  };
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
